### ISSUE TITLE
Idea atrevida para el libro

### ISSUE THREAD

**Issue by vencejo** [oslugr/curso-git#20]
Pues consiste simplemente en ponerle algunos dichos, dibujitos e ilustraciones.
En este sentido me parece genial el enfoque de uno de los tutores , @psicobyte , que hizo [una presentación genial](http://www.psicobyte.com/descargas/ZenDeGit.pdf) hace poco.
¿Por que no utilizar sus dichos taoistas y sus fotos en partes estratégicas del libro para darle un toque desenfadado a la vez que se asientan los materiales con ayuda de elementos gráficos?

**Comment by alfem** [comment]
I si aprovecháis "Fiverr"? Hay ilustradores, animadores, etc por 5$

**Comment by JJ** [comment]
Pues mira...
