### ISSUE TITLE
he terminado de leerlo y en paralelo he anotado erratas

### ISSUE THREAD

**Issue by manuti** [oslugr/curso-git#35]
Todas la erratas que he visto las he ido apuntando y las he corregido aquí.
Propongo cómo mejora final volver a ejecutar todos los comandos incluidos en el libro y verificar que los mensajes de salida que se obtienen siguen siendo los mismos.
un saludo y gracias por el libro y por compartir.

**Comment by JJ** [comment]
Muchísimas gracias :-)

**Comment by JJ** [comment]
He tenido que hacer capturas de algunos comandos porque no cabían en los márgenes. Lo que hace esto aún más complicado. ¿Todavía quieres que se ejecute esto? Verificar que el resultado es el mismo va a ser imposible, los repos habrán cambiado... Y hacerlo a mano sería un infierno.

**Comment by manuti** [comment]
No creo que sea necesario. Sería lo ideal y sería algo más para que haga un
tercero que quiera aportar algo más al proyecto o que lo esté haciendo todo
paso a paso y por tanto vaya a tener esa comprobación. Así solo tendría que
añadirla y listo.

**Comment by JJ** [comment]
Gracias por el comentario. Si todavía estás interesado, pon un issue [en el nuevo repo](https://github.com/JJ/aprende-git)
