### ISSUE TITLE
Dudas sobre el párrafo de mas_usos.md

### ISSUE THREAD

**Issue by josealberto4444** [oslugr/curso-git#36]
Hay un párrafo que dice:
Los submódulos pueden ser un ejemplo de flujos de trabajo: en este caso, hay un flujo desde “las fuentes del manantial” (que puede cambiar de forma independiente su proyecto) hasta “la desembocadura” (nuestro proyecto, que lo usa). Dividir un proyecto en módulos y dejar que personas independientes se encarguen de cada uno, integrándolo todo en un submódulo, por tanto, es una forma simple y sin demasiadas complicaciones de hacerlo.

¿La parte del final donde dice dividir un proyecto en módulos e integrarlo todo en un submódulo está bien? O bien no estoy entendiendo nada, o creo que debería ser algo así como:
Dividir un proyecto en submódulos y dejar que personas independientes se encarguen de cada uno, integrándolo todo en un repositorio, por tanto, es una forma simple y sin demasiadas complicaciones de hacerlo.

Si es eso último, solo tenéis que decirlo y lo añado a la próxima pull request que haga, en la que corregiré muchas erratas.

**Comment by JJ** [comment]
Creo que sí, es correcto. El problema es que existen los submódulos y no
existe el módulo del que descienden, que sería el propio repositorio. Si
crees que así se entiende mejor, modifícalo.

**Comment by josealberto4444** [comment]
Vale, pues entonces quizá lo mejor sería dejar la primera vez que se dice módulo y luego cambiar submódulo por repositorio:
Dividir un proyecto en módulos y dejar que personas independientes se encarguen de cada uno, integrándolo todo en un repositorio, por tanto, es una forma simple y sin demasiadas complicaciones de hacerlo.

¿Te parece así mejor?

**Comment by JJ** [comment]
El 9 de agosto de 2017, 16:55, josealberto4444 <notifications@github.com>
escribió:

> Vale, pues entonces quizá lo mejor sería dejar la primera vez que se dice
> módulo y luego cambiar submódulo por repositorio:
> Dividir un proyecto en módulos y dejar que personas independientes se
> encarguen de cada uno, integrándolo todo en un repositorio, por tanto, es
> una forma simple y sin demasiadas complicaciones de hacerlo.
>

No, es al revés. Módulo = repo. Quizás aclarar que en git a los módulos en
los que se divide un proyecto o repo se le llaman submódulos.

**Comment by josealberto4444** [comment]
Vale, ¿qué te parece lo siguiente? Es que creo que así se entiende mejor.

Los submódulos pueden ser un ejemplo de flujos de trabajo: en este caso, hay un flujo desde “las fuentes del manantial” (que puede cambiar de forma independiente su proyecto) hasta “la desembocadura” (nuestro proyecto, que lo usa). Dividir un proyecto en módulos (repositorios) y dejar que personas independientes se encarguen de cada uno, integrándolos en uno común en forma de submódulos dentro de él, por tanto, es una forma simple y sin demasiadas complicaciones de hacerlo.

**Comment by JJ** [comment]
No me acaba de gustar. A ver así
> integrando los módulos de cada uno en un repositorio común en forma de submódulos...

**Comment by josealberto4444** [comment]
Sí, me gusta y creo que es aclaratorio. Entonces sería esta la versión final, ¿no? En cuanto me confirmes te hago el PR.

> Los submódulos pueden ser un ejemplo de flujos de trabajo: en este caso, hay un flujo desde “las fuentes del manantial” (que puede cambiar de forma independiente su proyecto) hasta “la desembocadura” (nuestro proyecto, que lo usa). Dividir un proyecto en módulos (repositorios) y dejar que personas independientes se encarguen de cada uno, integrando los módulos de cada uno en un repositorio común en forma de submódulos, por tanto, es una forma simple y sin demasiadas complicaciones de hacerlo.

**Comment by JJ** [comment]
Sí, hazlo así :-)

**Comment by josealberto4444** [comment]
#39
